name: Publish JM_TEST

permissions:
  contents: write
  packages: write
  id-token: write

concurrency:
  group: JM_TEST-${{ github.head_ref || github.ref }}
  cancel-in-progress: true 

on:
  workflow_dispatch:
    inputs:
      selected_runner:
        description: Select the runner to use
        options:
          - ubuntu-latest
          - arc-runner-set
        default: ubuntu-latest
        type: choice
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ${{ inputs.selected_runner == 'arc-runner-set' && 'arc-runner-set' || 'ubuntu-latest'  }}
    outputs:
      image_url: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
      metatags: ${{ steps.meta.outputs.tags }}
      builddigest: ${{ steps.build-and-push.outputs.digest }}
      buildmetadata: ${{ steps.build-and-push.outputs.metadata }}
      buildimageid: ${{ steps.build-and-push.outputs.imageid }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          # Use the PR branch name if this is a PR, otherwise use main
          IMAGE_TAG: ${{ github.event.pull_request.head.ref || github.ref_name }}
      
      - name: Sign the published Docker image
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  deploy:
    runs-on: ${{ inputs.selected_runner == 'arc-runner-set' && 'arc-runner-set' || 'ubuntu-latest'  }}
    needs: 
      - build
    steps:
      - name: Deploy JM_TEST
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_URL: ${{ needs.build.outputs.image_url }}
        with:
          host: ${{ secrets.JM_TEST_SSH_IP }}
          username: ${{ secrets.JM_TEST_SSH_USER }}
          key: ${{ secrets.JM_TEST_SSH_PRIV_KEY }}
          port: ${{ secrets.JM_TEST_SSH_PORT }}
          envs: IMAGE_URL
          command_timeout: "25m"
          script: |
            echo $IMAGE_URL > .test-echo
            docker pull $IMAGE_URL
            sleep 1
            cd ~/servers/jm-test
            sleep 1
            # Use the source branch for PRs, or the current ref for pushes
            BRANCH_NAME=${{ github.head_ref || github.ref_name }}
            git checkout $BRANCH_NAME
            sleep 1
            git pull 
            sleep 1
            docker compose up -d --force-recreate

